<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Dalamud.NET.Sdk/15.0.0">
  <!-- Project settings -->
  <PropertyGroup>
    <Name>Yo-kai Check</Name>
    <Version>1.2.0</Version>
    <Author>Haselnussbomber</Author>
    <RepoUrl>https://github.com/Haselnussbomber/YokaiCheck</RepoUrl>
    <Punchline>Tracking assistant for Yo-kai Watch rewards.</Punchline>
    <Description>Yo-kai Check is a small plugin to assist you in tracking the rewards of the Yo-kai Watch event.</Description>
    <IconUrl>https://raw.githubusercontent.com/Haselnussbomber/YokaiCheck/main/YokaiCheck/Assets/Icon.png</IconUrl>
    <LoadRequiredState>1</LoadRequiredState>
    <CanUnloadAsync>true</CanUnloadAsync>
  </PropertyGroup>

  <!-- Build settings -->
  <PropertyGroup>
    <OutputPath>..\bin\</OutputPath>
    <DefineConstants>$(DefineConstants);AUTOCTOR_EMBED_ATTRIBUTES</DefineConstants>
  </PropertyGroup>

  <!-- Dalamud.NET.Sdk settings -->
  <PropertyGroup>
    <Use_Dalamud_Newtonsoft_Json>false</Use_Dalamud_Newtonsoft_Json>
  </PropertyGroup>

  <!-- Translations -->
  <ItemGroup Condition="Exists('Translations.json')">
    <EmbeddedResource Include="Translations.json" />
  </ItemGroup>

  <!-- Licenses -->
  <ItemGroup Condition="Exists('LICENSES.md')">
    <EmbeddedResource Include="LICENSES.md" />
    <None Include="LICENSES.md" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <!-- NuGet dependencies -->
  <ItemGroup>
    <PackageReference Include="AutoCtor" Version="3.1.0" PrivateAssets="all" ExcludeAssets="compile;runtime" />
    <PackageReference Include="Injectio" Version="6.1.0" PrivateAssets="all" />
  </ItemGroup>

  <!-- HaselCommon -->
  <ItemGroup>
    <ProjectReference Include="..\HaselCommon\HaselCommon\HaselCommon.csproj" />
  </ItemGroup>
</Project>
